trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Provision
  displayName: 'Creating terraform on Azure'
  jobs:
    - job: provision
      displayName: 'Provision container instance'
      pool:
        name: UTB
      variables: # vars from Azure DevOps in the library
      - group: azure
      steps:
        - script: |
            set -e 

            terraform init -input=false
            terraform apply -input=false -auto-approve
          name: 'RunTerraform'
          displayName: 'Run Terraform'
          env: # these vars are being passed from the variable library specified in Azure DevOps
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            TF_VAR_imagebuild: $(tag)
